### ISSUE TITLE
`Θ₀` missing in `:SimplestRealistic`?

### ISSUE THREAD

**Issue by navidcy** [glwagner/SeawaterPolynomials.jl#34]
Equation (17) by Roquet et al. (2015) mentions ``ρ' = R₁₀₀ Sᴬ  + R₀₁₀ (Θ - Θ₀) - R₀₂₀ Θ² - R₀₁₁ Θ Z`` while the docstring does not include the `Θ₀` term:

https://github.com/CliMA/SeawaterPolynomials.jl/blob/79045e7d140cde5ba21c86a5b7afe287108c2a21/src/SecondOrderSeawaterPolynomials.jl#L110-L112

Is it only a docstring problem? cc @glwagner

**Comment by jbisits** [comment]
After expanding equation (17) in Roquet et al. (2015) the `Θ₀` term becomes part of the `R₀₀₀` coeffcient in the polynomial form for seawater density (equation (6) in Roquet et al. (2015)). Because it has no effect on ocean dynamics it was removed. There is a discussion relating to this [here](https://github.com/CliMA/SeawaterPolynomials.jl/pull/28#issuecomment-1472897955).

**Comment by navidcy** [comment]
Should we add a remark in the docstring?

**Comment by jbisits** [comment]
> Should we add a remark in the docstring?

That is a good idea! I can get to it tomorrow if you like?

**Comment by navidcy** [comment]
That'd be great
